# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCYZ67_8ABMFTDudJR9vdMMmjjT1bfBm
"""

from google.colab import files
files.upload()

import pandas as pd

df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df.head()