# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCYZ67_8ABMFTDudJR9vdMMmjjT1bfBm
"""



from google.colab import files
import pandas as pd

uploaded = files.upload()

def cargar_y_limpiar_datos(ruta_csv: str) -> pd.DataFrame:
    df = pd.read_csv(ruta_csv)

    df['year'] = pd.to_datetime(df['year'], format='%Y')

    df["brand"] = df["name"].str.split().str[0]
    df["model"] = df["name"].str.split().str[1:].apply(lambda x: ' '.join(x))

    return df

ruta = "CAR DETAILS FROM CAR DEKHO.csv"
columnas = ['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
df = pd.read_csv(ruta, names=columnas, skiprows=1)

df = cargar_y_limpiar_datos(ruta)

df = df.drop(columns=["name"])

nuevo_orden = ['brand', 'model', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
df = df[nuevo_orden]

df.to_csv('datos_limpios.csv', index=False)
files.download('datos_limpios.csv')
