# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCYZ67_8ABMFTDudJR9vdMMmjjT1bfBm
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

def cargar_y_limpiar_datos(ruta_csv: str) -> pd.DataFrame:
    df = pd.read_csv(ruta_csv)

    df['year'] = pd.to_datetime(df['year'], format='%Y')

    df["brand"] = df["name"].str.split().str[0]
    df["model"] = df["name"].str.split().str[1:].apply(lambda x: ' '.join(x))

    return df

ruta = "CAR DETAILS FROM CAR DEKHO.csv"
columnas = ['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
df = pd.read_csv(ruta, names=columnas, skiprows=1)

df = cargar_y_limpiar_datos(ruta)

df = df.drop(columns=["name"])

nuevo_orden = ['brand', 'model', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
df = df[nuevo_orden]

df.to_csv('datos_limpios.csv', index=False)
files.download('datos_limpios.csv')

from google.colab import files
uploaded = files.upload()

import pandas as pd

def clasificar_precio(precio):
    if precio < 100000:
        return 'Barato'
    elif 100000 <= precio <= 400000:
        return 'Medio'
    else:
        return 'Caro'

def clasificar_auto(fecha):
    año = fecha.year
    if año < 2010:
        return 'Antiguo'
    elif 2010 <= año <= 2017:
        return 'Medio'
    else:
        return 'Reciente'


df = pd.read_csv('datos_limpios.csv')
df['year'] = pd.to_datetime(df['year'])

precios_promedio = df.groupby(['brand', 'model'])['selling_price'].mean().reset_index()
precios_promedio.columns = ['Marca', 'Modelo', 'Precio Promedio']
precios_promedio = precios_promedio.sort_values(by='Precio Promedio', ascending=False)

precios_promedio_marca = df.groupby('brand')['selling_price'].mean().reset_index()
precios_promedio_marca = precios_promedio_marca.sort_values(by='selling_price', ascending=False)

df['categoria_antiguedad'] = df['year'].apply(clasificar_auto)
df['categoria_precio'] = df['selling_price'].apply(clasificar_precio)
df['precios_promedio_marca'] = df['brand'].map(precios_promedio_marca.set_index('brand')['selling_price'])

df = df.sort_values(by='selling_price', ascending=False)

promedio_precio_antiguedad = df.groupby('categoria_antiguedad')['selling_price'].mean().reset_index()
promedio_precio_antiguedad.columns = ['Categoría de Antigüedad', 'Promedio de Precio']
promedio_precio_antiguedad = promedio_precio_antiguedad.sort_values(by='Promedio de Precio', ascending=False)

promedio_precio_categoria = df.groupby('categoria_precio')['selling_price'].mean().reset_index()
promedio_precio_categoria.columns = ['Categoría de Precio', 'Promedio de Precio']
promedio_precio_categoria = promedio_precio_categoria.sort_values(by='Promedio de Precio', ascending=False)

df[['brand', 'model', 'year', 'categoria_antiguedad']].to_csv('detalle_vehiculos.csv', index=False)
df[['brand', 'model', 'year', 'selling_price', 'categoria_precio']].to_csv('detalle_precio_categoria.csv', index=False)
precios_promedio[['Marca', 'Modelo', 'Precio Promedio']].to_csv('precios_promedio_modelo.csv', index=False)
precios_promedio_marca.to_csv('precios_promedio_marca.csv', index=False)
promedio_precio_antiguedad.to_csv('promedio_precio_antiguedad.csv', index=False)
promedio_precio_categoria.to_csv('promedio_precio_categoria.csv', index=False)

files.download('detalle_vehiculos.csv')
files.download('detalle_precio_categoria.csv')
files.download('precios_promedio_modelo.csv')
files.download('precios_promedio_marca.csv')
files.download('promedio_precio_antiguedad.csv')
files.download('promedio_precio_categoria.csv')