# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCYZ67_8ABMFTDudJR9vdMMmjjT1bfBm

# New Section
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kruskal
import scikit_posthocs as sp

df = pd.read_csv('datos_limpios.csv')
df['year'] = pd.to_datetime(df['year'])

def clasificar_auto(fecha):
    año = fecha.year
    if año < 2010:
        return 'Antiguo'
    elif 2010 <= año <= 2017:
        return 'Medio'
    else:
        return 'Reciente'

df['categoria_antiguedad'] = df['year'].apply(clasificar_auto)

antiguo = df[df['categoria_antiguedad'] == 'Antiguo']['selling_price']
medio = df[df['categoria_antiguedad'] == 'Medio']['selling_price']
reciente = df[df['categoria_antiguedad'] == 'Reciente']['selling_price']

stat, p = kruskal(antiguo, medio, reciente)
print("Prueba de Kruskal-Wallis - Antigüedad del Auto")
print(f"Estadístico H = {stat:.3f}")
print(f"p-valor = {p:.5f}")
print("⇒", "Diferencias significativas entre los grupos." if p < 0.05 else "No hay diferencias significativas.")

plt.figure(figsize=(10, 6))
sns.boxplot(x='categoria_antiguedad', y='selling_price', data=df, palette="Set2")
plt.title('Precio de Venta por Categoría de Antigüedad')
plt.xlabel('Antigüedad')
plt.ylabel('Precio de Venta (rupias)')
plt.grid(True)
plt.tight_layout()
plt.savefig('grafico_precio_antiguedad.png')
plt.show()

# Test de Dunn post-hoc
dunn_antiguedad = sp.posthoc_dunn(df, val_col='selling_price', group_col='categoria_antiguedad', p_adjust='bonferroni')
print("\nResultados del test de Dunn post-hoc (Bonferroni) - Antigüedad:")
print(dunn_antiguedad)

plt.figure(figsize=(8, 6))
sns.heatmap(dunn_antiguedad, annot=True, cmap='coolwarm', fmt=".3g")
plt.title('Test de Dunn - Antigüedad del auto')
plt.tight_layout()
plt.show()

grupos_fuel = [grupo['selling_price'].values for _, grupo in df.groupby('fuel')]
estadistico, pvalor = kruskal(*grupos_fuel)

print("\nPrueba de Kruskal-Wallis - Tipo de Combustible")
print(f"Estadístico H = {estadistico:.3f}")
print(f"p-valor = {pvalor:.5f}")
print("⇒", "Diferencias significativas entre los tipos de combustible." if pvalor < 0.05 else "No hay diferencias significativas.")

plt.figure(figsize=(10, 6))
sns.boxplot(x='fuel', y='selling_price', data=df, palette="Set3")
plt.title("Precio de Venta por Tipo de Combustible")
plt.xlabel("Tipo de Combustible")
plt.ylabel("Precio de Venta")
plt.grid(True)
plt.tight_layout()
plt.show()

# Test de Dunn post-hoc
dunn_combustible = sp.posthoc_dunn(df, val_col='selling_price', group_col='fuel', p_adjust='bonferroni')
print("\nResultados del test de Dunn post-hoc (Bonferroni) - Combustible:")
print(dunn_combustible)

plt.figure(figsize=(8, 6))
sns.heatmap(dunn_combustible, annot=True, cmap="coolwarm", fmt=".3f", cbar_kws={'label': 'p-valor'})
plt.title("Test de Dunn - Tipo de Combustible")
plt.tight_layout()
plt.show()