# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCYZ67_8ABMFTDudJR9vdMMmjjT1bfBm

# New Section
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter
import os
import string


def open_file(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: El archivo '{path}' no se encontró.")
        return ""


frase = open_file("texto.txt")
frase = frase.translate(str.maketrans("", "", string.punctuation)).lower()
palabras = frase.split()
all_words = " ".join(palabras)

wordcloud = WordCloud(
    background_color="white", min_font_size=5
).generate(all_words)

os.makedirs("img", exist_ok=True)

plt.figure(figsize=(5, 5), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.savefig("img/word_cloud.png")
plt.close()